export const demoProfile = {
  name: "Arjun Verma",
  email: "arjun.verma@example.com",
  age: 28,
  occupation: "Software Engineer",
  currency: "INR",
  financial_experience: "Intermediate",
  income_type: "Salaried",
  dependents: 1,
  salary_day: 1,
  credit_score: 765,
  risk_appetite: "Moderate",
  lifestyle_preference: "Balanced",
  primary_financial_goal: "Wealth Creation",
  monthly_income_tier: 3,
  monthly_income: 65000,
  other_income: 5000,
  monthly_expenses: [
    { category: "Housing", amount: 16000 },
    { category: "Food", amount: 8500 },
    { category: "Transport", amount: 3500 },
    { category: "Utilities", amount: 2500 },
    { category: "Shopping", amount: 4500 },
    { category: "Entertainment", amount: 3000 },
    { category: "Healthcare", amount: 1500 }
  ],
  detailed_expenses: [
    { category: "Housing", amount: 16000 },
    { category: "Food", amount: 8500 },
    { category: "Transport", amount: 3500 },
    { category: "Utilities", amount: 2500 },
    { category: "Shopping", amount: 4500 },
    { category: "Entertainment", amount: 3000 },
    { category: "Healthcare", amount: 1500 }
  ],
  savings_balance: 120000,
  emergency_fund: 90000,
  emergency_target: 200000,
  investments_balance: 240000,
  mutual_funds: 150000,
  stocks: 60000,
  fixed_deposits: 30000,
  gold: 25000,
  provident_fund: 85000,
  real_estate_value: 0,
  crypto_value: 0,
  total_debt: 180000,
  monthly_debt_payment: 8500,
  adaptive_needs_ratio: 45.0,
  adaptive_wants_ratio: 25.0,
  adaptive_savings_ratio: 30.0,
  target_needs_ratio: 45.0,
  target_wants_ratio: 25.0,
  target_savings_ratio: 30.0,
  goals: []
};
